---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 徐小帅.
--- DateTime: 2022/11/10 17:18
---

if(redis.call('get',KEYS[1])==ARGV[1])then
    return redis.call('delete',KEYS[1])
end
    return 0;